@startuml
left to right direction
skinparam packageStyle rect

:User: as user

rectangle "Safari"{
    user --> (Define dimensions of the safari \n and how many times should the simulation repeat)

    (Define dimensions of the safari \n and how many times should the simulation repeat) <.left. (Start the simulation): includes
    (Start the simulation) <.left. (Place animals and plants on safari): includes


    animal --> (Move)
    (Move) .left.> (Eat grass): extends
    (Move) .down.> (Eat leaves): extends
    (Move) ..> (Attack another animal): extends
    (Move) ..> (Reproduct animal): extends

    human --> (Shoot to the lion)

}
@enduml