@startuml
title Animal state diagram
[*] --> Initialised
MakingAction: check energyLevel
Sleeping: increase energyLevel
NoSleeping: move
Moving: decrease energyLevel
Reacting: check met object and react
Eating: increase energy energyLevel
Reproducing: make new animal
Settling: settle down
Checking: Chceck if enough moves in that iteration

Initialised --> MakingAction: put on the map
MakingAction --> Sleeping: fall asleep or continue sleeping
MakingAction --> NoSleeping: wake up or continue not sleeping
NoSleeping --> Moving: make move
Moving --> Reacting: found\n position
Reacting --> Settling: no object met
Reacting --> Eating: object to eat
Reacting --> Reproducing: object of the same type

Settling --> Checking
Eating --> Checking
Reproducing --> Checking

Checking --> Moving: yes
Checking --> [*]: no

@enduml